[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "revel_data_logging"
version = "0.1.8"
authors = [
    { name = "Miguel", email = "miguel.melo@driverevel.com" }
]
requires-python = ">=3.8"

[project.scripts]